current_version = "1.0.0"
commit = true
tag = true
message = "chore: bump {current_version} → {new_version}"
# parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(-(?P<stage>[^.]*)\.(?P<devnum>\d+))?'
# serialize = "{major}.{minor}.{patch}-{stage}.{devnum}"

# example part:
[part.stage]
type = "string"
values = ["alpha", "beta", "stable"]

[file."Cargo.toml"]
format = 'version = "{version}"'

[file."Cargo.lock"]
format = """name = "bump2version"
version = "{version}""""
