current_version = "0.1.4"
commit = true
tag = true
# parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(-(?P<stage>[^.]*)\.(?P<devnum>\d+))?'
# serialize = "{major}.{minor}.{patch}-{stage}.{devnum}"

# example part:
[part.stage]
type = "string"
values = ["alpha", "beta", "stable"]

[file."Cargo.toml"]
format = 'version = "{version}"'
